### ISSUE TITLE
Fix: input_pipe  not set correctly when two pipelines are merged

### ISSUE THREAD

**Issue by Treesarj** [EMMC-ASBL/otelib#110]
When two pipelines are merged, the input_pipe is set to the last pipe of the 2nd pipeline. This doesn't cause any technical issues as get() will get executed from the end but when fetching the configurations of the new merged pipeline its not possible to get the order of the filters.

eg: 
PipelineA= resource1>> mapping 1
PipelineB= resource2>> mapping 2
merged_pipeline= PipelineA>>PipelineB

execution works correctly but if we try to get the filters in the merged pipeline it gives:
merged_pipeline=resource1>> mapping 1>> mapping 2, which is wrong

**Comment by daniel-sintef** [comment]
I think this needs a unit test, which I'm working on. There is some strangeness going on. I can reproduce the error in a notebook, but then setting up in the context of a test causes the test to pass.

The reason why is that in the notebook I use the client.create_methods, while in the pytest methods we tend to just import the strategies directly. Even though both methods can construct pipelines, we only get problems when we use the client.create method. I will update this more when I make more progress.
