### ISSUE TITLE
Implement direct Python API usage

### ISSUE THREAD

**Issue by CasperWA** [EMMC-ASBL/otelib#52]
Implement a client that uses OTEAPI Core directly from the same Python interpreter environment and does not need an external server, i.e., OTEAPI Service.

**Comment by daniel-sintef** [comment]
- Essentially we are breaking up the client backend into two different 'versions':
    - A REST API handled by OTEAPI-services (how it is currently handled)
    - A python client (what we are developing now) 

- We plan on initializing both via `OTEClient` where we will either initialize the restapi-services or python backend as needed
   - We will add an explicit `backend` option of type `Enum` to specify which version, defaulting to restapi-service for backwards compatibility. 

- There will be an abstract base class common to both with public facing methods. 
   - We will implement client-specific private methods for each strategy, e.g., `_filter`

- The code will be organized such that there will be a core `backends` root directory, which one directory for each backend.
    - For each of these backends there will be a directory, `strategies` containing the strategies for each version of the backend.

**Comment by CasperWA** [comment]
This has been closed by #60
