### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/otelib#7]
- Document how to start oteapi-services both manually and with `docker-compose up -d`.
- Make sure that all examples are up to date and works.

**Comment by CasperWA** [comment]
This is documented in [oteapi-services](https://github.com/EMMC-ASBL/oteapi-services), I don't think there's a need to repeat the instructions here.

Making sure all examples are up to date is a continuous task, no issue is necessary.

Feel free to open a new issue(s) if you want to expand on the points above.

**Comment by CasperWA** [comment]
This is documented in [oteapi-services](https://github.com/EMMC-ASBL/oteapi-services), I don't think there's a need to repeat the instructions here.

Making sure all examples are up to date is a continuous task, no issue is necessary.

Feel free to open a new issue(s) if you want to expand on the points above.
