### ISSUE TITLE
Use flit instead of setuptools

### ISSUE THREAD

**Issue by CasperWA** [EMMC-ASBL/otelib#76]
Using the [flit](https://flit.pypa.io/) build system instead of [setuptools](https://setuptools.pypa.io/) in order to minimize root repository files.
Many Python package management files for setting up the package and handling requirements can be collected into a central file (`pyproject.toml`).
`flit` is also a more modern build system, optimized for simple Python packages.

**Comment by jesper-friis** [comment]
Not sure the time is right to introduce another packaging system. Better to concentrate on the content than the wrapping...

**Comment by CasperWA** [comment]
> Not sure the time is right to introduce another packaging system. Better to concentrate on the content than the wrapping...

Fair - but the work is already done, see #77
